name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Installieren von Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      # Terraform-Befehle ausf체hren
      - name: Execute Terraform Commands
        run: |
          cd Terraform/
          terraform init
          terraform apply -auto-approve

      # Ausgabe der Bucket-URL erfassen
      - name: Capture Bucket URL
        id: bucket_url
        run: echo "::set-output name=bucket_url::$(terraform output bucket_url)"

      # Installieren von Node.js und npm
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'latest'

      # Installieren der Anwendungsabh채ngigkeiten
      - name: Install Application Dependencies
        run: npm install

      # Tests ausf체hren
      - name: Run Tests
        run: npm test

      # Anwendung bauen
      - name: Build Application
        run: npm run build

      # Anwendung in S3 deployen
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ steps.bucket_url.outputs.bucket_url }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'build'

      # Bash-Skript ausf체hren
      - name: Run Bash Script
        run: |
          cd Terraform/
          ./bash.sh
